# -*- coding: utf-8 -*-
"""explorer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3eHfDXBzmG6J6ntK6JtZTpLof5C9ZZA
"""

import streamlit as st
from utils import load_image_and_metadata, display_metadata, get_ai_analysis, similarity_search, chat_about_artwork

def set_custom_styles():
    st.markdown(
        """
        <style>
        /* Import Google Fonts */
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Georgia:wght@400;700&display=swap');

        /* === Global & Base Styles === */

        /* Force body and the main Streamlit container to the desired background */
        body, html, #root, .stApp, .stApp > div:last-child {
            background-color: #FFEBAD !important;
            color: #333333 !important; /* Ensure default text color is correct */
            color-scheme: light !important; /* Force light color scheme to prevent dark mode defaults */
        }

        /* Crucial: Target the specific problematic Streamlit container */
        .st-emotion-cache-13k62yr {
            background: #FFEBAD !important; /* Override the dark blue background */
            color: #333333 !important; /* Ensure text color is dark */
            color-scheme: light !important; /* Crucial: Override dark color-scheme */
        }

        /* Header styling (make it disappear as it contains no elements) */
        header[data-testid="stHeader"] {
            background-color: #FFEBAD !important;
            height: 0px !important;
            min-height: 0px !important; /* Ensure minimal height */
            border-bottom: none !important;
            padding: 0 !important;
            margin: 0 !important;
        }

        /* Main content container (block-container) */
        .block-container {
            background-color: #FFEBAD !important;
            padding-top: 1rem;
            padding-bottom: 1rem;
            padding-left: 3rem;
            padding-right: 3rem;
        }

        /* All text elements */
        body, .stApp, .stApp *,
        /* Also target generic Streamlit text classes to ensure color consistency */
        .stMarkdown, .stText, .stLabel {
            font-family: 'Inter', sans-serif !important;
            color: #333333 !important;
        }

        /* Headers */
        h1, h2, h3, h4, h5, h6 {
            color: #333333 !important;
            font-family: 'Georgia', serif !important;
        }

        /* === Aggressive Streamlit DIV Resets === */
        /* Make almost all Streamlit-generated divs transparent and borderless by default. */
        /* This is to combat any other hidden dark backgrounds */
        div[data-testid],
        div[data-testid^="stVerticalBlock"],
        div[data-testid^="stHorizontalBlock"],
        .st-emotion-cache-*, /* Target all dynamic Streamlit classes */
        div.stMarkdown,
        div.stFileUploader,
        div.stSelectbox,
        div.stButton,
        div.stExpander,
        div.stChatInput,
        div.stChatMessage,
        div.stCode,
        div.element-container,
        div.main,
        div.stApp > div {
            background-color: transparent !important;
            border: none !important;
            box-shadow: none !important;
        }

        /* === Custom Component Styles === */

        /* File uploader dropzone (the area where you drag files) */
        /* Needs background and dashed border *within* the transparent parent */
        [data-testid="stFileUploaderDropzone"] {
            background-color: #FFEBAD !important; /* Matches main background */
            border: 2px dashed #C3BEF7 !important; /* Dashed border for visual cue */
            border-radius: 6px !important;
            color: #333333 !important;
            padding: 20px !important;
        }

        /* Browse files button inside uploader */
        [data-testid="stFileUploaderDropzone"] button {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            border: none !important;
            border-radius: 4px !important;
            padding: 8px 16px !important;
            font-weight: 600 !important;
        }

        /* FIX 1: Selectbox styling - target the dark blue background */
        .stSelectbox [data-baseweb="select"] {
            background-color: #C3BEF7 !important; /* Light purple background */
            border: none !important; /* Remove stroke */
            box-shadow: none !important;
            border-radius: 8px !important;
        }

        /* Selectbox input field */
        .stSelectbox input {
            background-color: transparent !important;
            color: #333333 !important;
            border: none !important;
            box-shadow: none !important;
        }

        /* Additional selectbox container targeting */
        .stSelectbox > div > div {
            background-color: #C3BEF7 !important;
            border: none !important;
            border-radius: 8px !important;
        }

        /* Target the specific selectbox control element */
        .stSelectbox [data-baseweb="select"] > div {
            background-color: #C3BEF7 !important;
            border: none !important;
        }

        /* Selectbox options dropdown */
        [data-baseweb="popover"] {
            background-color: #FFEBAD !important;
        }

        /* Selectbox options */
        [role="option"] {
            background-color: #FFEBAD !important;
            color: #333333 !important;
        }

        /* Selectbox options on hover */
        [role="option"]:hover {
            background-color: #ffda66 !important;
        }

        /* FIX 2: API Key Input Field in Sidebar */
        /* Target the text input field for API key */
        [data-testid="stTextInput"] input {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            border: none !important;
            border-radius: 8px !important;
            box-shadow: none !important;
        }

        /* Text input container */
        [data-testid="stTextInput"] > div {
            background-color: #C3BEF7 !important;
            border: none !important;
            border-radius: 8px !important;
        }

        /* Target the password input field specifically */
        [data-testid="stTextInput"] [data-baseweb="input"] {
            background-color: #C3BEF7 !important;
            border: none !important;
            border-radius: 8px !important;
        }

        /* Target the input wrapper */
        [data-testid="stTextInput"] [data-baseweb="base-input"] {
            background-color: #C3BEF7 !important;
            border: none !important;
            border-radius: 8px !important;
        }

        /* Target the eye icon button in password field - SPECIFIC FIX */
        [data-testid="stTextInput"] button[aria-label="Show password text"] {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            border: none !important;
        }

        /* Target the eye icon button with Streamlit classes */
        [data-testid="stTextInput"] button.st-b4 {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            border: none !important;
        }

        /* Additional targeting for password input components */
        .stTextInput div[data-baseweb="input"],
        .stTextInput div[data-baseweb="base-input"] {
            background-color: #C3BEF7 !important;
            border: none !important;
        }

        /* Target all buttons within text input */
        [data-testid="stTextInput"] button {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            border: none !important;
        }

        /* FIX 3: Bottom chat input section - fix the dark background */
        /* Target the chat input container more specifically */
        [data-testid="stChatInput"] {
            background-color: #FFEBAD !important; /* Match main background */
            border: 2px solid #C3BEF7 !important; /* Desired single border */
            border-radius: 8px !important;
            box-shadow: none !important;
        }

        /* Target the parent container of chat input that might have dark background */
        [data-testid="stChatInput"] > div,
        [data-testid="stChatInput"] .st-emotion-cache-* {
            background-color: #FFEBAD !important;
            border: none !important;
        }

        /* Remove any internal borders/backgrounds from chat input elements */
        [data-testid="stChatInput"] .st-emotion-cache-s1k4sy,
        [data-testid="stChatInput"] [data-baseweb="textarea"],
        [data-testid="stChatInput"] [data-baseweb="base-input"],
        [data-testid="stChatInput"] textarea
        {
            border: none !important;
            background-color: transparent !important;
            box-shadow: none !important;
        }

        /* Chat input field text color */
        [data-testid="stChatInput"] input,
        [data-testid="stChatInput"] textarea {
            color: #333333 !important;
        }

        /* Chat input placeholder text */
        [data-testid="stChatInput"] input::placeholder,
        [data-testid="stChatInput"] textarea::placeholder {
            color: #666666 !important;
        }

        /* Additional fix for chat input bottom section */
        .stChatInput {
            background-color: #FFEBAD !important;
        }

        /* Target any sticky footer or bottom container */
        [data-testid="stBottom"],
        .stChatInput [data-testid="stBottom"],
        div[style*="position: sticky"] {
            background-color: #FFEBAD !important;
        }

        /* AGGRESSIVE FIX: Target the bottom sticky container that holds chat input */
        /* This targets the dark blue bottom section */
        div[data-testid="stBottom"] {
            background-color: #FFEBAD !important;
            border-top: none !important;
        }

        /* Additional targeting for the bottom section container */
        .stChatInput div[data-testid="stBottom"] {
            background-color: #FFEBAD !important;
        }

        /* Target the specific bottom container element */
        div[style*="position: sticky"][style*="bottom: 0"] {
            background-color: #FFEBAD !important;
        }

        /* Chat messages container */
        [data-testid="stChatMessageContainer"] {
            background-color: #FFEBAD !important;
        }

        /* Individual chat messages */
        [data-testid="chatMessage"] {
            background-color: #FFEBAD !important;
        }

        /* Regular buttons */
        .stButton > button {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            border: none !important;
            border-radius: 8px !important;
            font-weight: 600 !important;
            padding: 0.5em 1em !important;
            box-shadow: none !important;
        }

        /* Images */
        img {
            max-height: 500px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }

        /* Expander headers */
        [data-testid="stExpander"] details summary {
            background-color: #C3BEF7 !important;
            color: #333333 !important;
            font-weight: 600 !important;
            padding: 10px !important;
            border-radius: 8px !important;
            border: none !important;
        }

        /* Sidebar styling */
        [data-testid="stSidebar"] {
            background-color: #FFEBAD !important;
            border-right: none !important;
        }

        [data-testid="stSidebar"] * {
            color: #333333 !important;
        }

        /* Analysis sections - Specific to comparer, but good to have consistency */
        .analysis-section {
            background-color: #FFFBEC;
            border: 2px solid #EADCA6;
            border-radius: 15px;
            padding: 20px;
            margin: 20px 0;
            box-shadow: none !important;
        }

        /* Final catch-all for any stubborn dark/blue/grey backgrounds */
        [style*="background-color: rgb(14, 17, 23)"],
        [style*="background-color: rgb(38, 39, 48)"],
        [style*="background-color: rgb(49, 51, 63)"],
        [style*="background-color: rgb(240, 242, 246)"],
        [style*="background-color: rgb(250, 250, 250)"]
        {
            background-color: #FFEBAD !important;
        }

        /* Additional aggressive targeting for dark backgrounds */
        div[style*="background"] {
            background-color: #FFEBAD !important;
        }
        /* Target any sticky footer or bottom container */
        [data-testid="stBottom"],
        .stChatInput [data-testid="stBottom"],
        div[style*="position: sticky"] {
            background-color: #FFEBAD !important;
        }

        /* AGGRESSIVE FIX: Target the bottom sticky container that holds chat input */
        /* This targets the dark blue bottom section */
        div[data-testid="stBottom"] {
            background-color: #FFEBAD !important;
            border-top: none !important;
        }

        /* Additional targeting for the bottom section container */
        .stChatInput div[data-testid="stBottom"] {
            background-color: #FFEBAD !important;
        }

        /* Target the specific bottom container element */
        div[style*="position: sticky"][style*="bottom: 0"] {
            background-color: #FFEBAD !important;
        }

        /* NEW FIX: Target the specific bottom block container that's causing the dark blue background */
        [data-testid="stBottomBlockContainer"] {
            background-color: #FFEBAD !important;
            border-top: none !important;
        }

        /* Target the emotion cache class for the bottom container */
        .st-emotion-cache-qdbtli {
            background-color: #FFEBAD !important;
            border-top: none !important;
        }

        /* Additional targeting for all elements within the bottom container */
        [data-testid="stBottomBlockContainer"] * {
            background-color: transparent !important;
        }

        /* Ensure the vertical block wrapper within bottom container is transparent */
        [data-testid="stBottomBlockContainer"] [data-testid="stVerticalBlockBorderWrapper"] {
            background-color: transparent !important;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

def explore_one_artwork(client, metadata, image_data):
    set_custom_styles()

    st.title("Explore One Artwork")

    # Reset functionality
    if st.button("Reset Selection"):
        st.rerun()

    # Put Select Artwork and Upload side by side with custom styling
    col1, col2 = st.columns(2)

    with col1:
        st.markdown('<div class="section-box">', unsafe_allow_html=True)
        st.markdown("### Select Artwork")
        image_ids = [fname.replace(".jpg", "") for fname in image_data.keys()]
        selected_id = st.selectbox("Choose from collection", image_ids, index=0)
        st.markdown('</div>', unsafe_allow_html=True) # Close the div for first artwork

    with col2:
        st.markdown('<div class="section-box">', unsafe_allow_html=True)
        st.markdown("### Or Upload Your Own")
        uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])
        st.markdown('</div>', unsafe_allow_html=True) # Close the div for second artwork

    if uploaded_file or selected_id:
        image, filename, meta = load_image_and_metadata(
            metadata,
            image_id=selected_id if not uploaded_file else None,
            uploaded_file=uploaded_file
        )

        if image:
            # Section title
            st.markdown("## Selected Artwork and Visually Similar Artworks")

            # Columns for original and similar artworks side by side
            col_orig, col_sim = st.columns([1, 2])

            with col_orig:
                st.image(image, caption=filename, use_column_width=True)
                # Ensure metadata display is not in an unwanted box
                if meta:
                    st.markdown(f"""
                    **Name:** {meta.get('name', 'Unknown')}
                    **Artist:** {meta.get('artist', 'Unknown')}
                    **Year:** {meta.get('year', 'Unknown')}
                    **Nationality:** {meta.get('nationality', 'Unknown')}
                    """)

            with col_sim:
                similarity_search(filename, image_data)

            # Initialize ai_analysis variable
            ai_analysis = None

            # AI Analysis section with expander
            with st.expander("AI Artwork Analysis", expanded=False):
                with st.spinner("Analyzing artwork..."):
                    ai_analysis = get_ai_analysis(client, image)
                st.markdown(f'<div class="analysis-section">{ai_analysis}</div>', unsafe_allow_html=True)

            # Chat section - only show if we have ai_analysis
            if ai_analysis:
                st.markdown("## Chat About This Artwork")
                st.markdown("Ask questions about the artwork's style, technique, historical context, or anything else you'd like to know!")

                chat_about_artwork(
                    client,
                    meta.get('name', 'Unknown') if meta else 'Unknown',
                    meta.get('artist', 'Unknown') if meta else 'Unknown',
                    meta.get('year', 'Unknown') if meta else 'Unknown',
                    meta.get('nationality', 'Unknown') if meta else 'Unknown',
                    ai_analysis
                )

        else:
            st.error("Error loading the image.")