# -*- coding: utf-8 -*-
"""streamlit_app_small_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQGoVuLFuV0W6ppNJs5ycowGQqEPqlbt
"""

#!pip install streamlit

import streamlit as st
import os
import json
import pandas as pd
from openai import OpenAI

# Set page config
st.set_page_config(page_title="Feminist Art Explorer & Analyzer", layout="wide")

# === DATA LOADING ===
metadata = pd.read_csv("metadata.csv", delimiter=';')
with open("image_vectors.json", "r") as f:
    image_data = json.load(f)
image_data = {key.replace("images/", ""): value for key, value in image_data.items()}

# === SIDEBAR SETTINGS ===
st.sidebar.title("Settings")
openai_api_key = st.sidebar.text_input("🔑 Enter OpenAI API Key", type="password")
page = st.sidebar.radio("Choose View", ["Explore One Artwork", "Compare Two Artworks"])

if not openai_api_key:
    st.warning("Please enter your OpenAI API key to continue.")
    st.stop()

client = OpenAI(api_key=openai_api_key)

# === MAIN APP LOGIC ===
from explorer import explore_one_artwork
from comparer import compare_two_artworks

if page == "Explore One Artwork":
    explore_one_artwork(client, metadata, image_data)
elif page == "Compare Two Artworks":
    compare_two_artworks(client, metadata, image_data)

